project_id = "lwbdmycbsssibotzwgeu"

[functions.generate-message]
verify_jwt = true

[functions.send-campaign]
verify_jwt = true

[functions.send-bulk-campaign]
verify_jwt = true

[functions.process-queue]
verify_jwt = true

[functions.test-webhook]
verify_jwt = true

[functions.search-google-places]
verify_jwt = true
